import cv2
import numpy as np
image=cv2.imread("/home/karthik/index")
cv2.imshow('image',image)
l = np.array([20,20,20])
u = np.array([230,230,230])
mask=cv2.inRange(image,l,u)
maski=cv2.bitwise_not(mask)
cv2.imshow('mask',mask)
cv2.imshow('maski',maski)
image1=cv2.bitwise_and(image,image,mask=mask)
image2=cv2.bitwise_and(image,image,mask=maski)
#image2=cv2.bitwise_and(image2,image,mask=mask)
res=cv2.add(image1,image2,mask=mask)
#res = cv2.cvtColor(res, cv2.COLOR_BGR2GRAY)
kernel = np.ones((5,5),np.uint8)
res1= cv2.morphologyEx(image, cv2.MORPH_CLOSE, kernel)
#cv2.imshow('mask1',mask1)
cv2.imshow('img1',image1)
cv2.imshow('img2',image2)
cv2.imshow('res',res)
cv2.imshow('res1',res1)
cv2.waitKey(0)
