import cv2
import numpy as np
image=cv2.imread("/home/karthik/images.jpeg")
cv2.imshow('image',image)
l = np.array([20,20,20])
u = np.array([230,230,230])
mask=cv2.inRange(image,l,u)
maski=cv2.bitwise_not(mask)
cv2.imshow('mask',mask)
cv2.imshow('maski',maski)
image1=cv2.bitwise_and(image,image,mask=mask)
image2=cv2.bitwise_and(image,image,mask=maski)
#image2=cv2.bitwise_and(image2,image,mask=mask)
res=cv2.add(image1,image2,mask=mask)
#res = cv2.cvtColor(res, cv2.COLOR_BGR2GRAY)
kernel = np.ones((5,5),np.uint8)
res1= cv2.morphologyEx(image, cv2.MORPH_CLOSE, kernel)
res2=cv2.bitwise_and(res1,res1,mask=maski)
#cv2.imshow('mask1',mask1)
res2=cv2.add(res1,res2)
#res3=cv2.cvtColor(res2,cv2.COLOR_BGR2GRAY)
#res1= cv2.equalizeHist(res1)
#ret,thresh=cv2.threshold(res3,100,255,0)
#contour,hie=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
#print len(contour)
#cv2.drawContours(res3,contour,-1,(0,255,0),3)
cv2.imshow('img1',image1)
cv2.imshow('img2',image2)
cv2.imshow('res',res)
cv2.imshow('res1',res1)
#cv2.imshow('thresh',thresh)
cv2.imshow('res3',res2)
cv2.waitKey(0)
